export const SET_SEED_DATA = 'UTILS/SET_SEED_DATA';
export const SET_MAINTENANCE_DATA = 'UTILS/SET_MAINTENANCE_DATA';
export const SET_COLOR_DATA = 'UTILS/SET_COLOR_DATA';
export const SET_SEEDTYPE_DATA = 'UTILS/SET_SEEDTYPE_DATA';
